### ISSUE TITLE
[SUPPORT] No module named dateutil

### ISSUE THREAD

**Issue by dolohow** [arvvoid/plugin.video.hbogoeu#118]
**Describe the bug**
When starting playback of series episode plugin crashes.

**Steps to reproduce**
Try to watch a series episode

**Expected behaviour**
Episode is being played.

## Debug log

```
Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named dateutil
  Traceback (most recent call last):
    File "/storage/.kodi/addons/plugin.video.hbogoeu/main.py", line 25, in <module>
      addon_main.router(REQUEST_PARAMS)
    File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/base.py", line 149, in router
      self.handler.episode(url)
    File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handlereu.py", line 1016, in episode
      self.addLink(episode, HbogoConstants.ACTION_PLAY)
    File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handlereu.py", line 1401, in addLink
      media_info = self.construct_media_info(title)
    File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handlereu.py", line 1347, in construct_me dia_info
      avail_datetime = Util.is_utc_datetime_past_now(availfrom)
    File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/util.py", line 19, in is_utc_datetime_pas t_now
      from dateutil import tz
ImportError: No module named dateutil

```

**Operating System**
LibreELEC on Linux (ARM)

**Comment by arvvoid** [comment]
Hello, dateutil (https://kodi.wiki/view/Add-on:Dateutil) is in the official Kodi repository it got installed automatically on add-on update but might not be loaded. Try to restart Kodi and then it should be fine.

**Comment by arvvoid** [comment]
@dolohow When you can please confirm if a simple restart solved your issue.

**Comment by dolohow** [comment]
Yes, it works after restart.  Thanks.
